// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.12
// source: bi_grpc.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	BIService_SalesByCategory_FullMethodName = "/xmlservice.BIService/SalesByCategory"
)

// BIServiceClient is the client API for BIService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BIServiceClient interface {
	SalesByCategory(ctx context.Context, in *CategoryRequest, opts ...grpc.CallOption) (*CategoryResponse, error)
}

type bIServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBIServiceClient(cc grpc.ClientConnInterface) BIServiceClient {
	return &bIServiceClient{cc}
}

func (c *bIServiceClient) SalesByCategory(ctx context.Context, in *CategoryRequest, opts ...grpc.CallOption) (*CategoryResponse, error) {
	out := new(CategoryResponse)
	err := c.cc.Invoke(ctx, BIService_SalesByCategory_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BIServiceServer is the server API for BIService service.
// All implementations must embed UnimplementedBIServiceServer
// for forward compatibility
type BIServiceServer interface {
	SalesByCategory(context.Context, *CategoryRequest) (*CategoryResponse, error)
	mustEmbedUnimplementedBIServiceServer()
}

// UnimplementedBIServiceServer must be embedded to have forward compatible implementations.
type UnimplementedBIServiceServer struct {
}

func (UnimplementedBIServiceServer) SalesByCategory(context.Context, *CategoryRequest) (*CategoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SalesByCategory not implemented")
}
func (UnimplementedBIServiceServer) mustEmbedUnimplementedBIServiceServer() {}

// UnsafeBIServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BIServiceServer will
// result in compilation errors.
type UnsafeBIServiceServer interface {
	mustEmbedUnimplementedBIServiceServer()
}

func RegisterBIServiceServer(s grpc.ServiceRegistrar, srv BIServiceServer) {
	s.RegisterService(&BIService_ServiceDesc, srv)
}

func _BIService_SalesByCategory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CategoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BIServiceServer).SalesByCategory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BIService_SalesByCategory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BIServiceServer).SalesByCategory(ctx, req.(*CategoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BIService_ServiceDesc is the grpc.ServiceDesc for BIService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BIService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "xmlservice.BIService",
	HandlerType: (*BIServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SalesByCategory",
			Handler:    _BIService_SalesByCategory_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "bi_grpc.proto",
}
