package main

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"log"
	"net"
	"strconv"
	"strings"

	"google.golang.org/grpc"
	pb "xmlservice/pb"
)

// ===== GENERATED BY protoc (simulated) =====
// In production: run: protoc --go_out=. --go-grpc_out=. *.proto

type ingestServiceServer struct {
	db *sql.DB
	pb.UnimplementedIngestServiceServer
}

type queryServiceServer struct {
	db *sql.DB
	pb.UnimplementedQueryServiceServer
}

// ===== Ingest Service Implementation =====

func (s *ingestServiceServer) IngestCSV(ctx context.Context, req *pb.IngestRequest) (*pb.IngestResponse, error) {
	log.Printf("[gRPC] IngestCSV request: %s", req.IdRequisicao)

	// Parse CSV from binary
	encomendas, err := parseOrdersFromCSV(io.NopCloser(strings.NewReader(string(req.CsvData))), &req.TaxRate)
	if err != nil {
		log.Printf("[gRPC] Validation error: %v", err)
		return &pb.IngestResponse{
			IdRequisicao: req.IdRequisicao,
			Status:       "ERRO_VALIDACAO",
			Error:        err.Error(),
		}, nil
	}

	// Build XML
	xmlBytes, err := buildXML(req.MapperVersion, encomendas)
	if err != nil {
		return &pb.IngestResponse{
			IdRequisicao: req.IdRequisicao,
			Status:       "ERRO_VALIDACAO",
			Error:        err.Error(),
		}, nil
	}

	// Persist to DB
	var documentID int64
	insertSQL := `INSERT INTO relatorio (xml_documento, mapper_version) VALUES ($1::xml, $2) RETURNING id`
	if err := s.db.QueryRowContext(ctx, insertSQL, string(xmlBytes), req.MapperVersion).Scan(&documentID); err != nil {
		log.Printf("[gRPC] Persistence error: %v", err)
		return &pb.IngestResponse{
			IdRequisicao: req.IdRequisicao,
			Status:       "ERRO_PERSISTENCIA",
			Error:        err.Error(),
		}, nil
	}

	// Send webhook
	go postWebhook(req.WebhookUrl, WebhookPayload{
		IDRequisicao: req.IdRequisicao,
		Status:       "OK",
		DocumentID:   documentID,
	})

	return &pb.IngestResponse{
		IdRequisicao: req.IdRequisicao,
		Status:       "OK",
		DocumentId:   documentID,
	}, nil
}

// ===== Query Service Implementation =====

func (s *queryServiceServer) GetSalesByCategory(ctx context.Context, req *pb.CategoryQuery) (*pb.SalesResult, error) {
	q := `
	WITH last_doc AS (
	  SELECT xml_documento
	  FROM relatorio
	  ORDER BY id DESC
	  LIMIT 1
	),
	vals AS (
	  SELECT unnest(xpath('//Item[@Categoria=' || quote_literal($1) || ']/ValorVenda/text()', xml_documento))::text AS v
	  FROM last_doc
	)
	SELECT COALESCE(SUM((v)::numeric), 0) AS total
	FROM vals;
	`

	var total float64
	if err := s.db.QueryRowContext(ctx, q, req.Category).Scan(&total); err != nil {
		return nil, err
	}

	return &pb.SalesResult{
		Category:    req.Category,
		TotalVendas: total,
	}, nil
}

func (s *queryServiceServer) GetProfitByRegion(ctx context.Context, req *pb.RegionQuery) (*pb.ProfitResult, error) {
	q := `
	WITH last_doc AS (
	  SELECT xml_documento
	  FROM relatorio
	  ORDER BY id DESC
	  LIMIT 1
	),
	encomendas AS (
	  SELECT unnest(xpath('//Encomenda[Cliente/Localizacao[@Regiao=' || quote_literal($1) || ']]', xml_documento)) AS e
	  FROM last_doc
	),
	lucros AS (
	  SELECT unnest(xpath('.//Item/Lucro/text()', e))::text AS p
	  FROM encomendas
	)
	SELECT COALESCE(SUM((p)::numeric), 0) AS lucro_total
	FROM lucros;
	`

	var lucro float64
	if err := s.db.QueryRowContext(ctx, q, req.Region).Scan(&lucro); err != nil {
		return nil, err
	}

	return &pb.ProfitResult{
		Region:      req.Region,
		LucroTotal:  lucro,
	}, nil
}

func (s *queryServiceServer) GetLossOrders(ctx context.Context, req *pb.LimitQuery) (*pb.LossOrdersResult, error) {
	q := `
	WITH last_doc AS (
	  SELECT xml_documento
	  FROM relatorio
	  ORDER BY id DESC
	  LIMIT 1
	),
	encomendas AS (
	  SELECT unnest(xpath('//Encomenda', xml_documento)) AS e
	  FROM last_doc
	),
	por_encomenda AS (
	  SELECT
	    (xpath('string(@Id)', e))[1]::text AS order_id,
	    COALESCE((
	      SELECT SUM((x::text)::numeric)
	      FROM unnest(xpath('.//Item/Lucro/text()', e)) AS t(x)
	    ), 0) AS lucro_total
	  FROM encomendas
	)
	SELECT order_id, lucro_total
	FROM por_encomenda
	WHERE lucro_total < 0
	ORDER BY lucro_total ASC
	LIMIT $1;
	`

	rows, err := s.db.QueryContext(ctx, q, req.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var result []*pb.LossOrder
	for rows.Next() {
		var orderId string
		var lucroTotal float64
		if err := rows.Scan(&orderId, &lucroTotal); err != nil {
			return nil, err
		}
		result = append(result, &pb.LossOrder{
			OrderId:    orderId,
			LucroTotal: lucroTotal,
		})
	}

	return &pb.LossOrdersResult{
		Results: result,
	}, nil
}

// ===== Start gRPC Servers =====

func startGRPCServers(db *sql.DB) error {
	// Ingest service on port 50051
	lis1, err := net.Listen("tcp", ":50051")
	if err != nil {
		return fmt.Errorf("failed to listen on :50051: %w", err)
	}

	s1 := grpc.NewServer()
	pb.RegisterIngestServiceServer(s1, &ingestServiceServer{db: db})
	log.Println("[gRPC] IngestService listening on :50051")

	go func() {
		if err := s1.Serve(lis1); err != nil {
			log.Printf("[gRPC] IngestService error: %v", err)
		}
	}()

	// Query service on port 50052
	lis2, err := net.Listen("tcp", ":50052")
	if err != nil {
		return fmt.Errorf("failed to listen on :50052: %w", err)
	}

	s2 := grpc.NewServer()
	pb.RegisterQueryServiceServer(s2, &queryServiceServer{db: db})
	log.Println("[gRPC] QueryService listening on :50052")

	go func() {
		if err := s2.Serve(lis2); err != nil {
			log.Printf("[gRPC] QueryService error: %v", err)
		}
	}()

	return nil
}
