syntax = "proto3";

package xmlservice;

option go_package = "xmlservice/pb";

// Service para queries complexas do BI
service QueryService {
  rpc GetSalesByCategory(CategoryQuery) returns (SalesResult);
  rpc GetProfitByRegion(RegionQuery) returns (ProfitResult);
  rpc GetLossOrders(LimitQuery) returns (LossOrdersResult);
}

message CategoryQuery {
  string category = 1;
}

message SalesResult {
  string category = 1;
  double totalVendas = 2;
}

message RegionQuery {
  string region = 1;
}

message ProfitResult {
  string region = 1;
  double lucroTotal = 2;
}

message LimitQuery {
  int32 limit = 1;
}

message LossOrder {
  string orderId = 1;
  double lucroTotal = 2;
}

message LossOrdersResult {
  repeated LossOrder results = 1;
}
